// ===================== DONNÉES =====================
const RACES = {
  'humain':{xp:30,pv:3,magie:0,chances:3,label:'Humain',
    info:'<b>Apprentissage rapide</b> · 30 XPs de départ. Peut choisir 2 compétences générales à rabais (–1 XP). Si carrière mixte : pas de surcoût XP.',
    faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],
    carrieresMustBe:null,
    carrieresInterdites:[]},
  'demi-elfe':{xp:28,pv:3,magie:0,chances:3,label:'Demi-Elfe',
    info:'<b>Semi-humain</b> · 28 XPs de départ. Accès à Archerie et Lecture & écriture (elfique) à rabais.',
    faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'elfe-gris':{xp:25,pv:3,magie:0,chances:3,label:'Elfe gris',
    info:'25 XPs de départ. Doit porter des oreilles d\'elfe.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'elfe-lunaire':{xp:25,pv:3,magie:0,chances:3,label:'Elfe lunaire',
    info:'25 XPs de départ. PV peut varier jour/nuit selon variante choisie. Doit porter des oreilles d\'elfe. Ne peut pas être de moralité maléfique.',
    faiblesses:'Varie selon variante',immunites:'Varie',
    moralitesInterdites:['malefique'],carrieresMustBe:null,carrieresInterdites:[]},
  'elfe-noir':{xp:25,pv:3,magie:0,chances:3,label:'Elfe noir',
    info:'25 XPs de départ. <b>Religion obligatoire : Atem\'ra</b> si compétence Religion achetée. Ne peut pas être bénéfique. Carrières interdites : Animiste.',
    faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:['benefique'],carrieresMustBe:null,carrieresInterdites:['animiste']},
  'elfe-sanguinaire':{xp:25,pv:3,magie:0,chances:3,label:'Elfe sanguinaire',
    info:'25 XPs de départ. <b>Religion obligatoire : Essence infernale</b>. Ne peut pas être bénéfique.',
    faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:['benefique'],carrieresMustBe:null,carrieresInterdites:[]},
  'elfe-sauvage':{xp:25,pv:3,magie:0,chances:3,label:'Elfe sauvage',
    info:'<b>Cueilleur né</b> · 25 XPs. Reçoit 5 plantes/scénario. Pas de Lecture & écriture (sauf elfique). Armure max métal souple. Apparence tribale requise.',
    faiblesses:'Aucune',immunites:'Jamais coma éthylique',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'etre-sylvestre':{xp:25,pv:3,magie:0,chances:3,label:'Être sylvestre',
    info:'<b>Aura de sérénité</b> · 25 XPs. Ne peut être attaqué en mêlée. Immunité à 1 élément au choix. Costume thématique requis.',
    faiblesses:'Élément opposé à l\'immunité choisie (+1 dégât)',immunites:'1 élément au choix',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'haut-elfe':{xp:25,pv:3,magie:0,chances:3,label:'Haut-Elfe',
    info:'<b>Héritage familial</b> · 25 XPs. 2 couronnes/scénario. Noblesse gratuite. Immunité charme et sommeil. Haine des orques. Oreilles d\'elfe requises. Carrières interdites : Barde, Berserker, Gardien mystique, Maître des runes, Maraudeur.',
    faiblesses:'Haine des orques',immunites:'Charme, Sommeil',
    moralitesInterdites:[],carrieresMustBe:null,
    carrieresInterdites:['barde','berserker','gardien-mystique','maitre-runes','maraudeur']},
  'nain':{xp:25,pv:4,magie:0,chances:3,label:'Nain',
    info:'<b>Mineur inné</b> · 25 XPs. <b>PV : 4</b>. Forge et Bravoure gratuites. Doit être ≤5ft7 ou porter costume approprié. Haine des orques. Barbe requise.',
    faiblesses:'Charme non résistable',immunites:'Alcool ×2 tolérance',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'gobelin':{xp:25,pv:3,magie:0,chances:3,label:'Gobelin',
    info:'<b>Alchimiste né</b> · 25 XPs. <b>PV : 2/jour, 4/nuit</b>. Forge gratuite. Armes max 90cm. Doit être ≤5ft8.',
    faiblesses:'Feu +1, Électricité +1',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'orque':{xp:25,pv:4,magie:0,chances:3,label:'Orque',
    info:'<b>Soif de sang</b> · 25 XPs. <b>PV : 4</b>. +1 dégât pendant un combat (arme 2 mains 110cm+) après avoir bu du sang. Ne peut pas être bénéfique.',
    faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:['benefique'],carrieresMustBe:null,carrieresInterdites:[]},
  'demi-demon':{xp:25,pv:4,magie:0,chances:3,label:'Demi-démon',
    info:'25 XPs. PV : 4. Doit avoir une carrière magique. Accès uniquement aux écoles de magie sombre. Ne peut pas être bénéfique.',
    faiblesses:'Eau/glace +1, Sacré +1',immunites:'Feu',
    moralitesInterdites:['benefique'],carrieresMustBe:null,carrieresInterdites:[]},
  'illithyd':{xp:25,pv:3,magie:0,chances:3,label:'Illithyd',
    info:'25 XPs. Costume distinctif obligatoire.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'norde':{xp:25,pv:4,magie:0,chances:3,label:'Norde',
    info:'25 XPs. <b>PV : 4</b>. Ne peut pas être bénéfique. Carrières possibles uniquement : Barbare, Berserker, Traqueur, Maraudeur, Maître des runes, Seigneur de guerre, Chaman, Druide, Animiste, Ermite, Gardien mystique, Rôdeur, Totem.',
    faiblesses:'Terre/acide +1',immunites:'Aucune',
    moralitesInterdites:['benefique'],
    carrieresMustBe:['barbare','berserker','traqueur','maraudeur','maitre-runes','seigneur-guerre','chaman','druide','animiste','ermite','gardien-mystique','rodeur','totem'],
    carrieresInterdites:[]},
  'presque-humain':{xp:25,pv:3,magie:0,chances:3,label:'Presqu\'Humain',
    info:'25 XPs.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'bossu':{xp:25,pv:3,magie:0,chances:3,label:'Bossu',
    info:'25 XPs.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'gitan':{xp:25,pv:3,magie:0,chances:3,label:'Gitan',
    info:'25 XPs. Carrières interdites : Berserker, Barbare.',faiblesses:'Performances (non résistable)',immunites:'Malédictions',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:['berserker','barbare']},
  'morgull':{xp:25,pv:3,magie:0,chances:4,label:'Morgull',
    info:'25 XPs. <b>4 chances au lieu de 3</b> par saison.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'arboreen':{xp:25,pv:3,magie:0,chances:3,label:'Arboréen',
    info:'25 XPs. Costume de félin requis.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'corvus':{xp:25,pv:3,magie:0,chances:3,label:'Corvus',
    info:'25 XPs. Costume de corbeau requis. Carrières permises : Roublard, Marchand, Mage et toutes les mixtes incluant au moins une de ces carrières.',
    faiblesses:'Feu +1',immunites:'Maladies',
    moralitesInterdites:[],
    carrieresMustBe:['roublard','marchand','mage','archer','barde','charlatan','ermite','garde','guerisseur','inquisiteur','maraudeur','scribe','traqueur','animiste','chaman','magelame','maitre-runes','sage'],
    carrieresInterdites:[]},
  'rasgadan':{xp:25,pv:3,magie:0,chances:3,label:'Rasgadan',
    info:'25 XPs. Costume de cornu requis. Ne peut pas être Berserker.',faiblesses:'Aucune',immunites:'Magie (résistance permanente)',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:['berserker']},
  'ratfolk':{xp:25,pv:3,magie:0,chances:3,label:'Ratfolk',
    info:'25 XPs. Costume de rat requis.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
  'saurien':{xp:25,pv:3,magie:0,chances:3,label:'Saurien',
    info:'25 XPs. Costume de reptile requis.',faiblesses:'Aucune',immunites:'Aucune',
    moralitesInterdites:[],carrieresMustBe:null,carrieresInterdites:[]},
};

const CARRIERES = {
  'barbare':{magie:false,ptsMagie:0,label:'Barbare',armes:'Toutes',armures:'4 pts',
    info:'Armes : toutes. Armures : 4 pts. <b>Privilège : Protection sauvage</b> (6 XP, permanent). Immunité aux fractures. Bravoure gratuite.',
    competences:{
      'generales':['Ambidextrie|3','Archerie|3','Arme à feu|3','Arme de jet|3','Arme non conventionnelle (91-130cm)|4','Arme non conventionnelle (131cm+)|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Forge|3','Héraldique|1','Lecture et écriture|2','Mulet de bataille|6','Noblesse|3','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],
      'carriere':['Attaque brutale|6','Bravoure accrue|6','Bris d\'arme|6','Brise-bouclier|6','Charge|5','Charge accrue|6','Coup meurtrier|4','Coup puissant|5','Endurance guerrière|3','Maître ambidextre|2','Onde de choc|6','Peinture de protection|4','Résistance à la torture|4','Résistance aux poisons|6','Résistance physique|6','Tir précis|6'],
      'privilege':['Protection sauvage|6'],
      'gratuit':['Bravoure']
    }},
  'combattant':{magie:false,ptsMagie:0,label:'Combattant',armes:'Toutes',armures:'Toutes',
    info:'Armes : toutes. Armures : toutes. <b>Privilège : Position de combat</b> (5 XP, permanent).',
    competences:{
      'generales':['Ambidextrie|3','Archerie|3','Arme à feu|3','Arme de jet|3','Arme non conventionnelle (91-130cm)|4','Arme non conventionnelle (131cm+)|6','Bouclier|2','Bravoure|4','Endurance simple|3','Forge|3','Héraldique|1','Lecture et écriture|2','Mulet de bataille|6','Noblesse|3','Résistance à l\'alcool|4','Résistance aux maladies|4'],
      'carriere':['Bouclier avancé|3','Bravoure accrue|6','Bris d\'arme|6','Charge|5','Charge accrue|6','Contre-charge|4','Coup meurtrier|4','Coup puissant|5','Désarmement|6','Endurance guerrière|3','Force brute|7','Maître ambidextre|2','Port d\'armure spécialisée|5','Résistance à la torture|4','Résistance physique|6','Tir précis|6'],
      'privilege':['Position de combat|5']
    }},
  'druide':{magie:true,ptsMagie:20,label:'Druide',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Magique</b>. Armes : 90 cm et moins. Armures : 3 pts. 20 pts de magie. Religion gratuite. École : Druidisme. <b>Privilège : Canalisation de la nature</b>.',
    competences:{
      'generales':['Archerie|3','Arme de jet|3','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Forge|3','Héraldique|1','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],
      'carriere':['Clairvoyance|5','Endurance naturelle à la magie|6','Fatigue atténuée|6','Ferveur magique|6','Haute magie|3','Magie brutale|5','Peinture de protection|4','Poudre de Morphée|3','Résistance aux poisons|6','Résistance magique|6','Résistance élémentaire|5','Résistance mentale|6','Restauration|6','Talisman|5','Talisman avancé|5','Transfert de vitalité en mana|2'],
      'privilege':['Canalisation de la nature|5'],
      'gratuit':['Religion']
    }},
  'mage':{magie:true,ptsMagie:20,label:'Mage',armes:'Bâton et dague',armures:'0 pt',
    info:'<b>Magique</b>. Armes : bâton et dague. Armures : 0 pt. 20 pts de magie. Religion gratuite. Écoles : Magie élémentaire, Nécromancie, Sortilèges. <b>Privilège : Concentration ou Masque du mage</b>.',
    competences:{
      'generales':['Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],
      'carriere':['Clairvoyance|5','Endurance naturelle à la magie|6','Fatigue atténuée|6','Ferveur magique|6','Haute magie|3','Magie brutale|5','Poudre de Morphée|3','Renvoi de sort|6','Résistance magique|6','Résistance élémentaire|5','Résistance mentale|6','Restauration|6','Talisman|5','Talisman avancé|5','Transfert de vitalité en mana|2'],
      'privilege':['Concentration (Sorcier)|5','Masque du mage (Illusionniste)|5'],
      'gratuit':['Religion']
    }},
  'marchand':{magie:false,ptsMagie:0,label:'Marchand',armes:'90 cm et moins',armures:'3 pts',
    info:'Armes : 90 cm et moins. Armures : 3 pts. <b>Privilège : Création accrue</b> (5 XP). Premier Contact marchand gratuit.',
    competences:{
      'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Forge|3','Héraldique|1','Lecture et écriture|2','Mulet de bataille|6','Noblesse|3','Résistance à l\'alcool|4','Résistance aux maladies|4'],
      'carriere':['Contact marchand : Brasseur|5','Contact marchand : Druide|5','Contact marchand : Forgeron|5','Contact marchand : Mineur|5','Contact marchand : Scribe|6','Contact marchand : Sorcier|10','Contact marchand : Commanditaire|10','Dissimulation d\'objet|6','Expert en concoction|5','Falsification|6','Forge avancée|6','Maître ambidextre|2','Maîtrise des poisons|5','Résistance aux poisons|6','Résistance mentale|6','Serrurier|5','Vol à la tire|4'],
      'privilege':['Création accrue|5'],
      'gratuit':['Contact marchand (1er)']
    }},
  'pretre':{magie:true,ptsMagie:20,label:'Prêtre',armes:'100 cm et moins',armures:'5 pts',
    info:'<b>Magique</b>. Armes : 100 cm et moins. Armures : 5 pts. 20 pts de magie. Religion et Messe gratuites. Écoles : Don, Magie noire, Voie maudite, Voie sacrée. Annule 1 attaque maudit/sacré par jour selon moralité.',
    competences:{
      'generales':['Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Héraldique|1','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],
      'carriere':['Armure de la foi|4','Attaque divine|5','Clairvoyance|5','Don miraculeux|5','Endurance naturelle à la magie|6','Ferveur magique|6','Haute magie|3','Magie brutale|5','Poudre de Morphée|3','Résistance magique|6','Résistance mentale|6','Restauration|6','Talisman|5','Talisman avancé|5','Transfert de vitalité en mana|2'],
      'privilege':['Messe|5'],
      'gratuit':['Religion','Messe']
    }},
  'roublard':{magie:false,ptsMagie:0,label:'Roublard',armes:'110 cm et moins',armures:'3 pts',
    info:'Armes : 110 cm et moins. Armures : 3 pts. <b>Privilège : Égorgement</b> (6 XP, 1×/jour cumulable).',
    competences:{
      'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Bouclier|2','Bravoure|4','Concoction : Toxicologie|5','Endurance simple|3','Forge|3','Héraldique|1','Lecture et écriture|2','Noblesse|3','Résistance à l\'alcool|4','Résistance aux maladies|4'],
      'carriere':['Attaque sournoise|4','Crochetage|5','Déguisement|4','Dissimulation d\'objet|6','Équilibre|6','Esquive|6','Falsification|6','Lame affûtée|4','Lancer meurtrier|4','Maître ambidextre|2','Maître de l\'évasion|6','Maître des poisons|5','Orientation planaire|3','Résistance à la torture|4','Résistance aux poisons|6','Tir précis|6','Torture|4','Touche à tout|4','Vol à la tire|4'],
      'privilege':['Égorgement|6']
    }},
  'animiste':{magie:true,ptsMagie:10,label:'Animiste',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Magique mixte</b>. 10 pts de magie. Accès : Druide + Roublard.',
    competences:{'generales':['Archerie|3','Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Héraldique|1','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Fatigue atténuée|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Poudre de Morphée|4','Restauration|7','Attaque sournoise|5','Crochetage|6','Esquive|7','Lame affûtée|5','Maître ambidextre|3','Vol à la tire|5'],'privilege':['Instinct animal|5'],'gratuit':['Religion']}},
  'archer':{magie:false,ptsMagie:0,label:'Archer',armes:'90 cm + arc',armures:'3 pts',
    info:'Mixte. Armes : 90 cm + arc. Armures : 3 pts. Accès : Combattant + Roublard. Archerie gratuite.',
    competences:{'generales':['Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Résistance à l\'alcool|4','Résistance aux maladies|4'],'carriere':['Archerie arcane|4','Bouclier avancé|4','Coup meurtrier|5','Désarmement|7','Endurance guerrière|4','Maître ambidextre|3','Résistance physique|7','Tir précis|7','Attaque sournoise|5','Crochetage|6','Équilibre|7','Esquive|7','Lancer meurtrier|5','Vol à la tire|5'],'privilege':['Tir en rafale|5'],'gratuit':['Archerie']}},
  'barde':{magie:false,ptsMagie:0,label:'Barde',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Roublard + Marchand.',
    competences:{'generales':['Archerie|3','Arme de jet|3','Bouclier|2','Bravoure|4','Concoction : Toxicologie|5','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4'],'carriere':['Attaque sournoise|4','Crochetage|5','Déguisement|4','Esquive|6','Falsification|6','Lame affûtée|4','Maître ambidextre|2','Vol à la tire|4','Contact marchand|5','Dissimulation d\'objet|6','Forge avancée|6','Résistance mentale|6','Serrurier|5'],'privilege':['Chant de guerre|4'],'gratuit':[]}},
  'berserker':{magie:false,ptsMagie:0,label:'Berserker',armes:'Toutes',armures:'4 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Barbare + Combattant. Rage meurtrière 1×/jour.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Résistance à l\'alcool|4'],'carriere':['Attaque brutale|7','Bravoure accrue|7','Bris d\'arme|7','Brise-bouclier|7','Charge|6','Charge accrue|7','Coup meurtrier|5','Coup puissant|6','Endurance guerrière|4','Bouclier avancé|4','Désarmement|7','Force brute|8','Résistance physique|7'],'privilege':['Rage meurtrière|4'],'gratuit':[]}},
  'chaman':{magie:true,ptsMagie:10,label:'Chaman',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Magique mixte</b>. 10 pts de magie. Accès : Druide + Marchand.',
    competences:{'generales':['Archerie|3','Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Restauration|7','Contact marchand|6','Dissimulation d\'objet|7','Falsification|7','Serrurier|6'],'privilege':['Invocation d\'esprit|4'],'gratuit':['Religion']}},
  'charlatan':{magie:false,ptsMagie:0,label:'Charlatan',armes:'90 cm et moins',armures:'3 pts',
    info:'Mixte. Accès : Marchand + Roublard.',
    competences:{'generales':['Archerie|3','Arme de jet|3','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Concoction : Toxicologie|5','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Résistance à l\'alcool|4'],'carriere':['Contact marchand|5','Dissimulation d\'objet|6','Expert en concoction|5','Falsification|6','Serrurier|5','Vol à la tire|4','Attaque sournoise|4','Crochetage|5','Déguisement|4','Esquive|6','Maître ambidextre|2','Maître des poisons|5'],'privilege':['Tour de passe-passe|4'],'gratuit':[]}},
  'ermite':{magie:false,ptsMagie:0,label:'Ermite',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Druide + Prêtre.',
    competences:{'generales':['Bâton de pouvoir|6','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Poudre de Morphée|4','Restauration|7','Armure de la foi|5','Attaque divine|6','Don miraculeux|6','Résistance magique|7','Résistance mentale|7','Talisman|6'],'privilege':['Méditation profonde|5'],'gratuit':['Religion']}},
  'garde':{magie:false,ptsMagie:0,label:'Garde',armes:'Toutes',armures:'Toutes',
    info:'Mixte. Accès : Combattant + Marchand.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Mulet de bataille|6','Noblesse|3','Résistance à l\'alcool|4'],'carriere':['Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Contre-charge|5','Coup meurtrier|5','Endurance guerrière|4','Force brute|8','Port d\'armure spécialisée|6','Résistance physique|7','Contact marchand|6','Dissimulation d\'objet|7','Serrurier|6'],'privilege':['Arrestation|4'],'gratuit':[]}},
  'gardien-mystique':{magie:false,ptsMagie:0,label:'Gardien mystique',armes:'Toutes',armures:'Toutes',
    info:'<b>Semi-magique mixte</b>. Accès : Combattant + Druide.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4'],'carriere':['Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Coup meurtrier|5','Endurance guerrière|4','Force brute|8','Résistance physique|7','Clairvoyance|6','Endurance naturelle à la magie|7','Haute magie|4','Magie brutale|6','Restauration|7','Talisman|6'],'privilege':['Vigilance absolue|5'],'gratuit':['Religion']}},
  'guerisseur':{magie:false,ptsMagie:0,label:'Guérisseur',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Prêtre + Marchand.',
    competences:{'generales':['Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4'],'carriere':['Armure de la foi|5','Attaque divine|6','Clairvoyance|6','Don miraculeux|6','Endurance naturelle à la magie|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Poudre de Morphée|4','Résistance magique|7','Restauration|7','Talisman|6','Contact marchand|6','Expert en concoction|6'],'privilege':['Soins d\'urgence|4'],'gratuit':['Religion']}},
  'inquisiteur':{magie:false,ptsMagie:0,label:'Inquisiteur',armes:'Toutes',armures:'5 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Prêtre + Combattant.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Mulet de bataille|6','Religion|0','Résistance à l\'alcool|4'],'carriere':['Armure de la foi|5','Attaque divine|6','Clairvoyance|6','Don miraculeux|6','Haute magie|4','Poudre de Morphée|4','Résistance magique|7','Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Coup meurtrier|5','Endurance guerrière|4','Force brute|8','Port d\'armure spécialisée|6'],'privilege':['Interrogatoire|5'],'gratuit':['Religion']}},
  'magelame':{magie:false,ptsMagie:0,label:'Magelame',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. Accès : Mage + Roublard.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Renvoi de sort|7','Résistance magique|7','Restauration|7','Attaque sournoise|5','Esquive|7','Lame affûtée|5','Maître ambidextre|3','Maître des poisons|6'],'privilege':['Lame magique|5'],'gratuit':['Religion']}},
  'maitre-runes':{magie:true,ptsMagie:10,label:'Maître des runes',armes:'Toutes',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. 10 pts de magie (niv. 1-5). Accès : Mage + Barbare. École : Magie élémentaire.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Fatigue atténuée|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Renvoi de sort|7','Résistance magique|7','Résistance élémentaire|6','Restauration|7','Attaque brutale|7','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Coup meurtrier|5','Endurance guerrière|4'],'privilege':['Runes de protection|6'],'gratuit':['Religion']}},
  'maraudeur':{magie:false,ptsMagie:0,label:'Maraudeur',armes:'Toutes',armures:'Toutes',
    info:'Mixte. Accès : Barbare + Marchand. <b>Privilège : Coup fracassant</b> (5 XP).',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Endurance simple|3','Héraldique|1','Mulet de bataille|6','Résistance à l\'alcool|4'],'carriere':['Attaque brutale|7','Bravoure accrue|7','Bris d\'arme|7','Brise-bouclier|7','Charge|6','Endurance guerrière|4','Maître ambidextre|2','Contact marchand|6','Dissimulation d\'objet|7','Falsification|3','Forge avancée|7','Maîtrise des poisons|6','Résistance aux poisons|6','Résistance mentale|7','Serrurier|6','Vol à la tire|5'],'privilege':['Coup fracassant|5'],'gratuit':[]}},
  'paladin':{magie:false,ptsMagie:10,label:'Paladin',armes:'Toutes',armures:'Toutes',
    info:'<b>Semi-magique mixte</b>. 10 pts de magie (niv. 1-5). Accès : Combattant + Prêtre. Religion et Invocation guerrière gratuites. Écoles : Don, Magie noire, Voie maudite, Voie sacrée.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Mulet de bataille|6','Noblesse|3','Religion|0','Résistance à l\'alcool|4','Rituel|4'],'carriere':['Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Contre-charge|5','Coup meurtrier|5','Désarmement|7','Endurance guerrière|4','Force brute|8','Port d\'armure spécialisée|6','Résistance physique|7','Armure de la foi|5','Attaque divine|6','Clairvoyance|6','Don miraculeux|6','Endurance naturelle à la magie|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Poudre de Morphée|4','Résistance magique|7','Résistance mentale|7','Restauration|7','Talisman|6','Transfert de vitalité en mana|3'],'privilege':['Ferveur divine|6'],'gratuit':['Religion','Invocation guerrière']}},
  'rodeur':{magie:false,ptsMagie:10,label:'Rôdeur',armes:'Toutes',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. 10 pts de magie (niv. 1-5). Accès : Combattant + Druide. Archerie et Religion gratuites. École : Druidisme.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4'],'carriere':['Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Charge|6','Contre-charge|5','Coup meurtrier|5','Désarmement|7','Endurance guerrière|4','Force brute|8','Port d\'armure spécialisée|7','Résistance physique|7','Tir précis|7','Clairvoyance|6','Endurance naturelle à la magie|7','Fatigue atténuée|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Peinture de protection|5','Poudre de Morphée|4','Résistance aux poisons|7','Résistance magique|7','Résistance élémentaire|6','Restauration|7','Talisman|6','Transfert de vitalité en mana|3'],'privilege':['Ennemi juré|6'],'gratuit':['Archerie','Religion']}},
  'sage':{magie:true,ptsMagie:20,label:'Sage',armes:'90 cm et moins',armures:'0 pt',
    info:'<b>Magique mixte</b>. 20 pts de magie. Accès : Prêtre + Mage. Peut prier 2 divinités (1 arcane + 1 divine). Religion et Lecture & écriture gratuites.',
    competences:{'generales':['Bâton de pouvoir|6','Bravoure|4','Concoction : Alchimie|5','Concoction : Herboristerie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],'carriere':['Armure de la foi|5','Attaque divine|6','Clairvoyance|5','Don miraculeux|6','Endurance naturelle à la magie|6','Ferveur magique|6','Haute magie|3','Magie brutale|5','Poudre de Morphée|3','Résistance magique|6','Résistance mentale|6','Restauration|6','Talisman|5','Talisman avancé|5','Transfert de vitalité en mana|2','Fatigue atténuée|7','Renvoi de sort|7','Résistance élémentaire|6'],'privilege':['Magie puissante|4'],'gratuit':['Religion','Lecture et écriture']}},
  'scribe':{magie:false,ptsMagie:10,label:'Scribe',armes:'90 cm et moins',armures:'0 pt',
    info:'<b>Semi-magique mixte</b>. 10 pts de magie (niv. 1-5). Accès : Mage + Marchand. Lecture & écriture gratuite. <b>Privilège : Parchemins magiques</b>.',
    competences:{'generales':['Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Alchimie|5','Endurance simple|3','Invocation guerrière|3','Lecture et écriture|2','Religion|0','Résistance à l\'alcool|4','Résistance aux maladies|4','Rituel|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Fatigue atténuée|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Renvoi de sort|7','Résistance magique|7','Résistance élémentaire|6','Transfert de vitalité en mana|3','Contact marchand|6','Dissimulation d\'objet|7','Expert en concoction|6','Falsification|7','Forge avancée|7'],'privilege':['Parchemins magiques|2 (par niveau)'],'gratuit':['Lecture et écriture']}},
  'seigneur-guerre':{magie:false,ptsMagie:0,label:'Seigneur de guerre',armes:'Toutes',armures:'Toutes',
    info:'Mixte. Accès : Combattant + Barbare.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Endurance simple|3','Héraldique|1','Mulet de bataille|6','Noblesse|3','Résistance à l\'alcool|4'],'carriere':['Bouclier avancé|4','Bravoure accrue|7','Bris d\'arme|7','Brise-bouclier|7','Charge|6','Charge accrue|7','Contre-charge|5','Coup meurtrier|5','Coup puissant|6','Désarmement|7','Endurance guerrière|4','Force brute|8','Maître ambidextre|2','Onde de choc|7','Port d\'armure spécialisée|6','Résistance à la torture|5','Résistance physique|7'],'privilege':['Cri de guerre|4'],'gratuit':[]}},
  'totem':{magie:true,ptsMagie:10,label:'Totem',armes:'90 cm et moins',armures:'3 pts',
    info:'<b>Semi-magique mixte</b>. 10 pts de magie (niv. 1-5). Accès : Druide + Roublard. Doit prendre "Langage animal" comme premier sort. École : Druidisme.',
    competences:{'generales':['Archerie|3','Bâton de pouvoir|6','Bouclier|2','Bravoure|4','Concoction : Herboristerie|5','Concoction : Toxicologie|5','Endurance simple|3','Invocation guerrière|3','Religion|0','Résistance à l\'alcool|4'],'carriere':['Clairvoyance|6','Endurance naturelle à la magie|7','Fatigue atténuée|7','Ferveur magique|7','Haute magie|4','Magie brutale|6','Peinture de protection|5','Poudre de Morphée|4','Restauration|7','Attaque sournoise|5','Crochetage|6','Déguisement|5','Esquive|7','Lame affûtée|5','Maître ambidextre|3','Maître des poisons|6','Vol à la tire|5'],'privilege':['Spiritualité animale|5'],'gratuit':['Religion']}},
  'traqueur':{magie:false,ptsMagie:0,label:'Traqueur',armes:'110 cm et moins',armures:'3 pts',
    info:'Mixte. Accès : Barbare + Roublard. Arme de jet et Lancer meurtrier (1er achat) gratuits.',
    competences:{'generales':['Ambidextrie|3','Archerie|3','Arme de jet|3','Arme non conventionnelle|4','Bouclier|2','Bravoure|4','Concoction : Toxicologie|5','Endurance simple|3','Héraldique|1','Lecture et écriture|2','Résistance à l\'alcool|4'],'carriere':['Attaque brutale|7','Bravoure accrue|7','Bris d\'arme|7','Brise-bouclier|7','Charge|6','Endurance guerrière|4','Maître ambidextre|2','Onde de choc|7','Résistance à la torture|4','Résistance aux poisons|6','Résistance physique|7','Attaque sournoise|5','Crochetage|6','Déguisement|5','Dissimulation d\'objet|7','Équilibre|7','Esquive|7','Falsification|7','Lame affûtée|5','Lancer meurtrier|5','Maître de l\'évasion|7','Maître des poisons|6','Orientation planaire|4','Résistance à la torture|4','Tir précis|6','Torture|5','Touche à tout|5','Vol à la tire|5'],'privilege':['Traque|6'],'gratuit':['Arme de jet','Lancer meurtrier (1er)']}}
};

const DIVINITES = {
  'Arawn':{moralites:['balancee','malefique'],ecoles:['Nécromancie','Dons','Magie noire']},
  'Argonas':{moralites:['balancee','benefique','malefique'],ecoles:['Dons','Magie noire','Sortilèges','Nécromancie']},
  'Asmodérus':{moralites:['malefique','balancee'],ecoles:['Voie maudite','Sortilèges','Magie noire','Dons']},
  "Atem'ra":{moralites:['malefique'],ecoles:['Nécromancie','Voie maudite','Magie noire']},
  'Cyrder':{moralites:['balancee'],ecoles:['Druidisme','Dons','Magie élémentaire']},
  'Elûna':{moralites:['benefique','balancee'],ecoles:['Druidisme','Dons']},
  'Leviastis':{moralites:['malefique'],ecoles:['Nécromancie','Voie maudite','Magie noire','Sortilèges','Magie élémentaire']},
  'Lumer':{moralites:['benefique','balancee'],ecoles:['Voie sacrée','Dons','Magie élémentaire']},
  'Magystia':{moralites:['benefique','balancee'],ecoles:['Sortilèges','Magie élémentaire','Nécromancie']},
  'Maskorino':{moralites:['benefique','malefique','balancee'],ecoles:['Dons','Magie noire','Sortilèges']},
  'Myrkar':{moralites:['benefique','balancee'],ecoles:['Dons','Magie élémentaire','Sortilèges']},
  'Thurdek':{moralites:['benefique','balancee'],ecoles:['Dons','Magie élémentaire']},
  'Vermilord':{moralites:['malefique','balancee'],ecoles:['Magie noire','Voie maudite','Nécromancie','Druidisme']},
  'Vorn':{moralites:['malefique'],ecoles:['Nécromancie','Voie maudite','Magie noire','Magie élémentaire']},
  'Walërya':{moralites:['benefique','malefique'],ecoles:['Voie maudite','Voie sacrée','Sortilèges']},
  'Amida':{moralites:['benefique','balancee'],ecoles:['Voie sacrée','Dons','Druidisme']},
  'Baku':{moralites:['benefique','balancee'],ecoles:['Voie sacrée','Dons','Druidisme']},
  'Izanagi & Izanami':{moralites:['benefique','malefique'],ecoles:['Voie sacrée','Dons','Magie noire','Nécromancie','Voie maudite']},
  'O-Kuni-Nushi':{moralites:['benefique','malefique','balancee'],ecoles:['Druidisme','Dons','Sortilèges','Magie élémentaire','Nécromancie']},
  'Baldur':{moralites:['benefique'],ecoles:['Voie sacrée','Magie élémentaire','Dons']},
  'Eir':{moralites:['benefique'],ecoles:['Dons','Voie sacrée']},
  'Honir':{moralites:['balancee'],ecoles:['Dons','Sortilèges']},
  'Magni':{moralites:['benefique','balancee'],ecoles:['Magie élémentaire','Dons']},
  'Modi':{moralites:['benefique','balancee'],ecoles:['Dons']},
  'Thrud':{moralites:['benefique','balancee'],ecoles:['Druidisme','Dons','Magie élémentaire']},
  'Vali':{moralites:['balancee','malefique'],ecoles:['Voie maudite','Sortilèges']},
  'Vidar':{moralites:['benefique','malefique','balancee'],ecoles:['Dons','Magie noire']},
  'Adramelech':{moralites:['malefique'],ecoles:['Nécromancie','Druidisme','Voie maudite','Magie noire']},
  'Baphomet':{moralites:['malefique'],ecoles:['Voie maudite','Magie noire','Nécromancie']},
  'Malveria':{moralites:['malefique'],ecoles:['Nécromancie','Druidisme','Magie noire','Voie maudite']},
  'Salazaar':{moralites:['malefique'],ecoles:['Magie noire','Magie élémentaire']},
  'Thalia':{moralites:['malefique'],ecoles:['Voie maudite','Sortilèges','Magie noire','Nécromancie']},
  'Essence infernale':{moralites:['malefique'],ecoles:['Magie noire','Sortilèges','Voie maudite','Magie élémentaire']},
  'Esprits de la guerre':{moralites:['benefique','balancee','malefique'],ecoles:['Dons','Druidisme','Magie élémentaire','Voie sacrée','Voie maudite','Magie noire']},
  'Esprits de la Nature':{moralites:['balancee','benefique','malefique'],ecoles:['Druidisme','Dons','Magie noire']},
  'Esprits des Morts':{moralites:['benefique','malefique','balancee'],ecoles:['Nécromancie','Druidisme']},
};

const SORTS = {
  'Dons':{1:['Bénédiction sacrée','Repos serein','Protection contre le mal'],2:['Soins','Lumière céleste','Détection des mensonges'],3:['Sanctuaire divin','Purgation','Apaisement'],4:['Courage','Peau de cuir','Cure divine'],5:['Cercle de guérison','Geôle divine','Armure miraculeuse'],6:['Ancre des souvenirs','Soins accrus','Festin des héros'],7:['Consécration','Délivrance des malédictions','Arme sainte'],8:['Armure divine','Régénération osseuse','Grâce divine'],9:['Cercle de restauration','Révélation','Seconde chance'],10:['Souffle de vie','Toucher divin','Avatar divin']},
  'Druidisme':{1:['Détection de la magie','Langage animal','Endurance druidique'],2:['Soins de la nature','Purification druidique','Amitié animale'],3:['Épines','Lumière solaire','Morsure d\'arachnide'],4:['Peau d\'écorce','Faiblesse aux poisons','Apaisement'],5:['Cercle de guérison druidique','Antidote','Enchevêtrement'],6:['Marque sauvage','Festin des druides','Animation d\'hommes-plantes'],7:['Source druidique','Cercle des ronces','Rayon de rouille'],8:['Voyage sylvestre','Arbres gardiens'],9:['Cercle de restauration druidique','Régénération sylvestre','Piège de racines'],10:['Souffle de vie','Reviviscence sylvestre','Avatar de la chasse sauvage']},
  'Magie élémentaire':{1:['Arme élémentaire mineure','Protection élémentaire','Faiblesse élémentaire'],2:['Toucher du mage','Rayon désarmant','Métabolisme de glace'],3:['Bouclier de vent','Rayon élémentaire','Sérénité élémentaire'],4:['Arme brûlante','Armure de pierre','Arme de titane'],5:['Boule élémentaire mineure','Renvoi élémentaire','Maîtrise des éléments'],6:['Jambes pétrifiées','Explosion élémentaire','Fracture élémentaire'],7:['Passage des brasiers','Bouclier de vent majeur','Vapeur Corrosive'],8:['Golem élémentaire','Prison de glace'],9:['Aspect élémentaire','Fusion élémentaire'],10:['Avatar élémentaire']},
  'Magie noire':{1:['Voile de la moralité','Bénédiction ténébreuse','Protection contre le bien'],2:['Peur maléfique','Fragmentation d\'armure','Voile de l\'ombre'],3:['Soins','Sanctuaire du mal','Damnation'],4:['Couardise','Peau de cuir','Drain infernal de l\'essence'],5:['Geôle des ombres','Armure ténébreuse'],6:['Cercle de guérison','Festin des vilains','Bouclier de la honte'],7:['Grâce ténébreuse','Désacralisation','Confusion sensorielle'],8:['Armure maléfique','Destruction d\'armure','Délivrance des malédictions'],9:['Marque du damné','Fracturation d\'arme','Symbole d\'occultation'],10:['Souffle de vie','Avatar ténébreux','Agonie divine']},
  'Nécromancie':{1:['Main morte','Langage des morts','Infliction de douleur'],2:['Sort de peur','Détection de la magie','Projectile d\'os'],3:['Animation mineure de zombies','Souffle du spectre'],4:['Silence de mort','Testament nécromantique'],5:['Animation de squelettes','Mort illusoire'],6:['Explosion cadavérique','Nécrophobie','Animation majeure de zombies'],7:['Main de la faucheuse','Prison d\'os','Voyage astral'],8:['Projectiles mortels','Toucher maudit','Échange de vitalité'],9:['Aspect macabre','Ordre d\'outre-tombe','Animation d\'un nécrophage'],10:['Invocation de la mort','Souffle de la faucheuse']},
  'Sortilèges':{1:['Détection de la magie','Force mentale','Poussée du mage'],2:['Identification','Projectiles arcanes mineurs','Rayon désarmant'],3:['Silence arcane','Sommeil de Morphée','Barrière magique'],4:['Objet maudit','Enchantement d\'arme','Cage de verre enchantée'],5:['Désenchantement arcane','Oubli','Occultation d\'objet'],6:['Incompétence','Projectiles arcanes majeurs','Fracture arcane'],7:['Drainage de mana','Création de souvenir','Toucher de dissipation de la magie'],8:['Voile d\'invisibilité','Domination','Consécration arcane'],9:['Chaos mental','Magie exhaustive','Aura d\'anti-magie'],10:['Dissipation de la magie','Fureur arcane','Incarnation arcane']},
  'Voie maudite':{1:['Souffrance maligne','Bénédiction malveillante','Détection de la magie'],2:['Langue de vipère','Voile de l\'ombre','Damnation'],3:['Fureur provoquée','Soins','La dernière chance'],4:['Prison de démence','Volonté infernale','Bouclier de la foi noire'],5:['Arme infernale','Emblème maudit','Protection infernale'],6:['Protection maligne contre la magie','Armure miraculeuse','Enclume du mal'],7:['Destruction des lieux','Dissipation de l\'âme','Désacralisation'],8:["L'art de la douleur",'Châtiment','Arsenal éthéré des abysses'],9:['Domination','Déchéance du guerrier','Voyage dans les ténèbres'],10:['Armée maléfique','Avatar maléfique']},
  'Voie sacrée':{1:['Bénédiction sacrée','Détection des morts et des démons','Protection contre le mal'],2:['Détection des mensonges','Purgation','Bastion de la foi'],3:['Vade Retro','Soins','Lumière purificatrice'],4:['Prison du jugement','Volonté divine','Bouclier de la foi'],5:['Arme sainte','Emblème sacré','Protection divine'],6:['Armure miraculeuse','Protection divine contre la magie','Cercle de guérison sacré'],7:['Révélation','Consécration','Purification des lieux'],8:['Arsenal éthéré de la foi','Châtiment','Rappel à la terre'],9:['Foudre purificatrice','Arsenal miraculeux','Seconde chance sacrée'],10:['Avatar sacré','Souffle de vie sacré']},
};

